///
/// @Generated by Mockolo
///



import Foundation
@testable import MockoloDemo


class ErrorFlowingMock: ErrorFlowing {
    
    private var _doneInit = false
    
    init() { _doneInit = true }

    var startCallCount = 0
    var startHandler: (() -> ())?
    func start()  {
        startCallCount += 1
        if let startHandler = startHandler {
            startHandler()
        }
        
    }
}

class SucccessFlowingMock: SucccessFlowing {
    
    private var _doneInit = false
    
    init() { _doneInit = true }

    var startCallCount = 0
    var startHandler: (() -> ())?
    func start()  {
        startCallCount += 1
        if let startHandler = startHandler {
            startHandler()
        }
        
    }
}

class NetworkingMock: Networking {
    
    private var _doneInit = false
    
    init() { _doneInit = true }

    var fetchDataCallCount = 0
    var fetchDataHandler: ((((Data?) -> Void)) -> ())?
    func fetchData(completion: ((Data?) -> Void))  {
        fetchDataCallCount += 1
        if let fetchDataHandler = fetchDataHandler {
            fetchDataHandler(completion)
        }
        
    }
}

